server:
  port: 8001
spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/cyx441984694/spring-cloud-config.git
          search-paths: config-repo
          username:
          password:
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8760/eureka/