server:
  port: 8001
spring:
  application:
    name: spring-cloud-config-server
  cloud:
    bus:
      trace:
        enabled: true
    config:
      server:
        git:
          uri: https://github.com/cyx441984694/spring-cloud-config.git
          search-paths: config-repo
          username:
          password:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8760/eureka/

management:
  endpoints:
    web:
      exposure:
        include: bus-refresh,httptrace
